<?php

namespace App\Http\Resources\Api;

use Illuminate\Http\Resources\Json\JsonResource;

class IncidentResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            'id'               => $this->id,
            'temporary_id'     => $this->temporary_id,
            'incident_reference_number' => $this->incident_reference_number,
            'title'            => $this->title,
            'description'      => $this->incident_description ?? $this->description,
            'incident_type_id' => $this->incident_type_id,
            'incident_type' => $this->whenLoaded('incidentType', fn () => [
                'id' => $this->incidentType?->id,
                'name' => $this->incidentType?->name,
                'code' => $this->incidentType?->code,
            ]),
            'location'         => $this->location,
            'location_id' => $this->location_id,
            'location_detail' => $this->whenLoaded('incidentLocation', fn () => [
                'id' => $this->incidentLocation?->id,
                'name' => $this->incidentLocation?->name,
                'code' => $this->incidentLocation?->code,
                'type' => $this->whenLoaded('incidentLocation', fn () => [
                    'id' => $this->incidentLocation?->locationType?->id,
                    'name' => $this->incidentLocation?->locationType?->name,
                ]),
            ]),
            'other_location' => $this->other_location,
            'datetime'         => $this->datetime?->toIso8601String(),
            'incident_date' => $this->incident_date?->toDateString(),
            'incident_time' => $this->incident_time?->format('H:i:s'),
            'classification'   => $this->classification,
            'classification_id' => $this->classification_id,
            'classification_detail' => $this->whenLoaded('incidentClassification', fn () => [
                'id' => $this->incidentClassification?->id,
                'name' => $this->incidentClassification?->name,
                'code' => $this->incidentClassification?->code,
            ]),
            'reclassification_id' => $this->reclassification_id,
            'reclassification_detail' => $this->whenLoaded('reclassification', fn () => [
                'id' => $this->reclassification?->id,
                'name' => $this->reclassification?->name,
                'code' => $this->reclassification?->code,
            ]),
            'status'           => $this->status,
            'status_id' => $this->status_id,
            'status_detail' => $this->whenLoaded('incidentStatus', fn () => [
                'id' => $this->incidentStatus?->id,
                'name' => $this->incidentStatus?->name,
                'code' => $this->incidentStatus?->code,
            ]),
            'work_package_id' => $this->work_package_id,
            'work_package' => $this->whenLoaded('workPackage', fn () => [
                'id' => $this->workPackage?->id,
                'name' => $this->workPackage?->name,
                'code' => $this->workPackage?->code,
            ]),
            'immediate_response' => $this->immediate_response,
            'subcontractor_id' => $this->subcontractor_id,
            'subcontractor' => $this->whenLoaded('subcontractor', fn () => [
                'id' => $this->subcontractor?->id,
                'name' => $this->subcontractor?->name,
                'contact_person' => $this->subcontractor?->contact_person,
                'contact_number' => $this->subcontractor?->contact_number,
            ]),
            'person_in_charge' => $this->person_in_charge,
            'subcontractor_contact_number' => $this->subcontractor_contact_number,
            'gps_location' => $this->gps_location,
            'activity_during_incident' => $this->activity_during_incident,
            'type_of_accident' => $this->type_of_accident,
            'basic_effect' => $this->basic_effect,
            'conclusion' => $this->conclusion,
            'close_remark' => $this->close_remark,
            'rootcause_id' => $this->rootcause_id,
            'root_cause' => $this->whenLoaded('rootCause', fn () => [
                'id' => $this->rootCause?->id,
                'name' => $this->rootCause?->name,
                'code' => $this->rootCause?->code,
            ]),
            'other_rootcause' => $this->other_rootcause,
            'reported_by'      => $this->reported_by,
            'reporter'         => new UserResource($this->whenLoaded('reporter')),
            'attachments'      => $this->whenLoaded('attachments', fn () => $this->attachments->map(fn ($a) => [
                'id'            => $a->id,
                'url'           => $a->url,
                'attachment_type_id' => $a->attachment_type_id,
                'attachment_type' => $a->attachmentType?->name,
                'attachment_category_id' => $a->attachment_category_id,
                'attachment_category' => $a->attachmentCategory?->name,
                'filename' => $a->filename,
                'original_name' => $a->original_name,
                'path' => $a->path,
                'description' => $a->description,
                'mime_type'     => $a->mime_type,
                'size'          => $a->size,
                'temporary_id' => $a->temporary_id,
                'local_created_at' => $a->local_created_at?->toIso8601String(),
                'created_at' => $a->created_at?->toIso8601String(),
                'updated_at' => $a->updated_at?->toIso8601String(),
            ])),
            'chronologies' => $this->whenLoaded('chronologies', fn () => $this->chronologies->map(fn ($entry) => [
                'id' => $entry->id,
                'event_date' => $entry->event_date?->toDateString(),
                'event_time' => $entry->event_time?->format('H:i:s'),
                'events' => $entry->events,
                'sort_order' => $entry->sort_order,
                'temporary_id' => $entry->temporary_id,
                'local_created_at' => $entry->local_created_at?->toIso8601String(),
                'created_at' => $entry->created_at?->toIso8601String(),
                'updated_at' => $entry->updated_at?->toIso8601String(),
            ])),
            'victims' => $this->whenLoaded('victims', fn () => $this->victims->map(fn ($victim) => [
                'id' => $victim->id,
                'victim_type_id' => $victim->victim_type_id,
                'victim_type' => $victim->victimType?->name,
                'name' => $victim->name,
                'identification' => $victim->identification,
                'occupation' => $victim->occupation,
                'age' => $victim->age,
                'nationality' => $victim->nationality,
                'working_experience' => $victim->working_experience,
                'nature_of_injury' => $victim->nature_of_injury,
                'body_injured' => $victim->body_injured,
                'treatment' => $victim->treatment,
                'temporary_id' => $victim->temporary_id,
                'local_created_at' => $victim->local_created_at?->toIso8601String(),
            ])),
            'witnesses' => $this->whenLoaded('witnesses', fn () => $this->witnesses->map(fn ($witness) => [
                'id' => $witness->id,
                'name' => $witness->name,
                'designation' => $witness->designation,
                'identification' => $witness->identification,
                'temporary_id' => $witness->temporary_id,
                'local_created_at' => $witness->local_created_at?->toIso8601String(),
            ])),
            'investigation_team_members' => $this->whenLoaded('investigationTeamMembers', fn () => $this->investigationTeamMembers->map(fn ($member) => [
                'id' => $member->id,
                'name' => $member->name,
                'designation' => $member->designation,
                'contact_number' => $member->contact_number,
                'company' => $member->company,
                'temporary_id' => $member->temporary_id,
                'local_created_at' => $member->local_created_at?->toIso8601String(),
            ])),
            'damages' => $this->whenLoaded('damages', fn () => $this->damages->map(fn ($damage) => [
                'id' => $damage->id,
                'damage_type_id' => $damage->damage_type_id,
                'damage_type' => $damage->damageType?->name,
                'estimate_cost' => $damage->estimate_cost,
                'temporary_id' => $damage->temporary_id,
                'local_created_at' => $damage->local_created_at?->toIso8601String(),
            ])),
            'immediate_actions' => $this->whenLoaded('immediateActions', fn () => $this->immediateActions->map(fn ($action) => [
                'id' => $action->id,
                'action_taken' => $action->action_taken,
                'company' => $action->company,
                'temporary_id' => $action->temporary_id,
                'local_created_at' => $action->local_created_at?->toIso8601String(),
            ])),
            'planned_actions' => $this->whenLoaded('plannedActions', fn () => $this->plannedActions->map(fn ($action) => [
                'id' => $action->id,
                'action_taken' => $action->action_taken,
                'expected_date' => $action->expected_date?->toDateString(),
                'actual_date' => $action->actual_date?->toDateString(),
                'temporary_id' => $action->temporary_id,
                'local_created_at' => $action->local_created_at?->toIso8601String(),
            ])),
            'immediate_causes' => $this->whenLoaded('immediateCauses', fn () => $this->immediateCauses->map(fn ($cause) => [
                'id' => $cause->id,
                'name' => $cause->name,
                'code' => $cause->code,
            ])),
            'contributing_factors' => $this->whenLoaded('contributingFactors', fn () => $this->contributingFactors->map(fn ($factor) => [
                'id' => $factor->id,
                'name' => $factor->name,
                'code' => $factor->code,
            ])),
            'work_activities' => $this->whenLoaded('workActivities', fn () => $this->workActivities->map(fn ($activity) => [
                'id' => $activity->id,
                'name' => $activity->name,
                'code' => $activity->code,
            ])),
            'external_parties' => $this->whenLoaded('externalParties', fn () => $this->externalParties->map(fn ($party) => [
                'id' => $party->id,
                'name' => $party->name,
                'code' => $party->code,
            ])),
            'comments' => $this->whenLoaded('comments', fn () => $this->comments->map(fn ($comment) => [
                'id' => $comment->id,
                'comment_type' => $comment->comment_type,
                'comment' => $comment->comment,
                'user' => [
                    'id' => $comment->user?->id,
                    'name' => $comment->user?->name,
                ],
                'replies' => $comment->replies->map(fn ($reply) => [
                    'id' => $reply->id,
                    'reply' => $reply->reply,
                    'user' => [
                        'id' => $reply->user?->id,
                        'name' => $reply->user?->name,
                    ],
                    'created_at' => $reply->created_at?->toIso8601String(),
                ]),
                'created_at' => $comment->created_at?->toIso8601String(),
            ])),
            'comments_count'   => $this->whenLoaded('comments', fn () => $this->comments->count()),
            'rejection_reason' => $this->rejection_reason,
            'submitted_at'     => $this->submitted_at?->toIso8601String(),
            'approved_at'      => $this->approved_at?->toIso8601String(),
            'rejected_at'      => $this->rejected_at?->toIso8601String(),
            'local_created_at' => $this->local_created_at?->toIso8601String(),
            'deleted_at'       => $this->deleted_at?->toIso8601String(),
            'created_at'       => $this->created_at?->toIso8601String(),
            'updated_at'       => $this->updated_at?->toIso8601String(),
        ];
    }
}
